### ISSUE TITLE
Availability of unspliced neurosphere data?

### ISSUE THREAD

**Issue by adamgayoso** [hansenlab/tricycle_paper_figs#2]
I can't seem to find the spliced and unspliced counts for the neurosphere data. Would it be possible to add the anndata used for scvelo to zenodo? Thanks!

**Comment by sjczheng** [comment]
I will add another qs file that has spliced counts, unspliced counts, and all outputs from the scvelo for neurosphere data.
We run scvelo in R, and we did not generate an anndata file.

Best,
Shijie

**Comment by sjczheng** [comment]
You can now access the new qs file that has the unspliced counts under the v1.1 zendo repo (https://doi.org/10.5281/zenodo.5835163). 
You could convert the SingleCellExperiment object to anndata format.

**Comment by adamgayoso** [comment]
Thanks!
